name: pacbio-hdv-v2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - openjdk=17
  # core tools
  - minimap2=2.26
  - samtools=1.19.2
  - bedtools=2.30.0
  - seqkit=2.10.0
  - cutadapt=4.9
  - bcftools
  - nanoplot
  - multiqc
  - racon
  # libs for RVHaplo
  - numpy
  - scipy
  - pandas>=1.1.3
  - biopython
  - matplotlib
  - pysam
  - pyfaidx
  - networkx
  - xopen
  - mcl
  # medaka - updated to compatible version
  - medaka>=1.11.0
  - pip:
      - tqdm
